made the code cleaner

diff --git a/performance-evolution-analysis b/performance-evolution-analysis
--- a/performance-evolution-analysis
+++ b/performance-evolution-analysis
@@ -10,8 +10,12 @@ touch failed_projects.txt
 for project in $( find . -maxdepth 1 -mindepth 1 -type d )
 do
     cd $2
-    mkdir $project-costs
-    mkdir $2/$project-outputs
+
+    project_costs_folder=$2/${project}-costs
+    project_outputs_folder=$2/outputs/${project}-outputs
+
+    mkdir ${project_costs_folder}
+    mkdir -p ${project_outputs_folder}
 
     counter=0
     cd $1/$project
@@ -22,16 +26,21 @@ do
     do
         cd $1/$project
         counter=$((counter+1))
+        counter_in_filename=`printf %06d $counter`
+
         echo $counter 
 
         git checkout -f $commit
-        infer run --cost-only -- mvn clean package -DskipTests &> $2/$project-outputs/$counter-$commit.txt
+        timeout 120 infer run --cost-only -- mvn clean package -DskipTests &> ${project_outputs_folder}/${counter_in_filename}-$commit.txt
 
         cd infer-out
-        cp costs-report.json $2/$project-costs
 
-        counter_in_filename=`printf %06d $counter`
-        mv $2/$project-costs/costs-report.json $2/$project-costs/$counter_in_filename-$commit.json
+        if [[ -e costs-report.json ]]
+        then
+            cp costs-report.json ${project_costs_folder}/${counter_in_filename}-$commit.json
+        else
+            echo "Cost report for ${project} in commit ${commit} could not be generated"
+        fi
 
         if [ $counter -gt $3 ]
         then 
@@ -40,14 +49,14 @@ do
 
         if [ $counter -gt 5 ] && [ $flag = true ];then
             flag=false
-            if ! [[ $(ls -A "$2/$project-costs") ]] ; then
+            if ! [[ $(ls -A "${project_costs_folder}") ]] ; then
                 echo $project---maven-does-not-compile >> $1/failed_projects.txt
-                rm -rf $2/$project-costs
+                rm -rf ${project_costs_folder}
                 break
 
-            elif ! [[ -s $2/$project-costs/$counter-$commit.json ]] ; then
+            elif ! [[ -s ${project_costs_folder}/${counter_in_filename}-$commit.json ]] ; then
                 echo $project---cost-report-empty >> $1/failed_projects.txt
-                rm -rf $2/$project-costs
+                rm -rf ${project_costs_folder}
                 break
             fi
         fi
